/*
 * Afficheur_Sept_Segg.c
 *
 *  Created on: 8 nov. 2023
 *      Author: alexi & alix
 */

/**
 * @file Afficheur_Sept_Segg.c
 * @brief Implémentation des fonctions pour l'affichage sur l'afficheur à sept segments.
 */

#include "Afficheur_Sept_Seg.h"

/**
 * @brief Affiche un chiffre sur l'afficheur à sept segments.
 *
 * Cette fonction configure les broches de l'afficheur à sept segments
 * pour afficher le chiffre spécifié.
 *
 * @param[in] chiffre - Le chiffre à afficher (de 0 à 9).
 */
void afficher_7_seg(int chiffre) {
    if (chiffre == 0) {
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 0);
    } else if (chiffre == 1) {
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 0);
    } else if (chiffre == 2) {
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 0);
    } else if (chiffre == 3) {
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 0);
    } else if (chiffre == 4) {
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 0);
    } else if (chiffre == 5) {
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 0);
    } else if (chiffre == 6) {
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 0);
    } else if (chiffre == 7) {
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 0);
    } else if (chiffre == 8) {
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 1);
    } else if (chiffre == 9) {
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 1);
    }
}
