/*
 * Afficheur_Sept_Seg.c
 *
 *  Created on: 8 nov. 2023
 *      Author: alexi & alix
 */

#include "Afficheur_Sept_Seg.h"

void afficher_7_seg(int chiffre) {
    if (chiffre==0){
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 0);
    }
    else if (chiffre==1){
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 0);
    }
    else if (chiffre==2){
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 0);
    }
    else if (chiffre==3){
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 0);
    }
    else if (chiffre==4){
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 0);
    }
    else if (chiffre==5){
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 0);
    }
    else if (chiffre==6){
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 0);
    }
    else if (chiffre==7){
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 0);
    }
    else if (chiffre==8){
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 1);
    }
    else if (chiffre==9){
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_1, 1);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_2, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_3, 0);
        HAL_GPIO_WritePin(BROCHE_DRIVER_7_SEGMENTS, BROCHE_DRIVER_SEGMENTS_4, 1);
    }
}
